# Generated by Django 3.0.3 on 2020-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200815_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aaa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
