# Generated by Django 3.0.3 on 2020-08-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_subpage_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
