# Generated by Django 3.0.3 on 2020-08-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default=None, max_length=100, null=True)),
                ('navbar_display', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
