# Generated by Django 3.0.3 on 2020-08-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('in_html', models.CharField(blank=True, max_length=150)),
                ('level', models.CharField(choices=[('OWNED', 'Owned'), ('FAMILIAR', 'Familiar'), ('FUTURE', 'Future')], default='FUTURE', max_length=10)),
            ],
        ),
    ]
