# Generated by Django 3.0.3 on 2020-08-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
