# Generated by Django 2.2.15 on 2020-08-26 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('contact_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
