# Generated by Django 3.0.3 on 2020-08-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.CharField(choices=[('DONE', 'Done'), ('ONGOING', 'Ongoing'), ('FUTURE', 'Future')], default='FUTURE', max_length=10),
        ),
    ]
