# Generated by Django 3.0.3 on 2020-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_html',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
